{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: assignment-app-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: assignment-app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecrets.aws.secretStoreName }}
    kind: SecretStore

  target:
    name: assignment-app-db-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque

  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecrets.aws.rdsSecretName }}
        property: {{ .Values.externalSecrets.aws.usernameKey }}

    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecrets.aws.rdsSecretName }}
        property: {{ .Values.externalSecrets.aws.passwordKey }}
{{- end }}