{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.aws.secretStoreName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: assignment-app
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.externalSecrets.aws.roleArn | quote }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region }}
{{- end }}