apiVersion: v2
name: assignment-app
version: 1.0.0
description: Assignment application using pawaPay base chart

dependencies:
  - name: application-helm
    version: "0.0.15"
    repository: "https://pawapay.github.io/application-helm"