application-helm:
  applicationName: assignment-app
  environment: dev

  deployment:
    enabled: true
    replicas: 1

    image:
      repository: "821106082324.dkr.ecr.us-east-1.amazonaws.com/assignment-app"
      tag: "v1"
      pullPolicy: Always

    # 🚫 Disable all probes from dependency chart (removes actuator probe)
    probes: null

    env:
      - name: PORT
        value: "8080"

      - name: DB_HOST
        value: "assignmentdb.cxdujekzuvzp.us-east-1.rds.amazonaws.com"

      - name: DB_PORT
        value: "5432"

      - name: DB_NAME
        value: "postgres"

      - name: DB_SSL
        value: "true"

      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: assignment-app-db-secret
            key: username

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: assignment-app-db-secret
            key: password

  service:
    type: ClusterIP
    ports:
      - web: 8080
    ingress_port: 8080

  ingresses:
    enabled: true
    manifests:
      - nameSuffix: ""
        annotations:
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/target-type: ip
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
        hosts:
          - host: ""
            paths:
              - "/client-ip"
              - "/client-ip/list"

externalSecrets:
  enabled: true
  aws:
    region: us-east-1
    secretStoreName: aws-secretstore
    roleArn: arn:aws:iam::821106082324:role/ExternalSecretsRole
    rdsSecretName: assignment/rds/creds
    usernameKey: username
    passwordKey: password